commerce_payment.commerce_payment_gateway.plugin.epayco_standard:
  type: commerce_payment_gateway_configuration
  mapping:
    p_cust_id_cliente:
      type: string
      label: 'Client ID'
    p_key:
      type: string
      label: 'Secret key'